from datetime import datetime
from sqlalchemy.orm import Session
from . import models


def seed(db: Session) -> None:
    """Idempotent seed — skips if data already exists."""
    if db.query(models.CaseGroup).count() > 0:
        return

    # ── Groups ──────────────────────────────────────────────
    g_test    = models.CaseGroup(name="test")
    g_support = models.CaseGroup(name="客服服务")
    g_ops     = models.CaseGroup(name="运营增长")
    db.add_all([g_test, g_support, g_ops])
    db.flush()

    # ════════════════════════════════════════════════════════
    # test 组
    # ════════════════════════════════════════════════════════
    d_new = models.CaseDirectory(
        name="new发", path="new发", group_id=g_test.id, sort_order=0
    )
    db.add(d_new)
    db.flush()

    db.add_all([
        # ── 原有 6 条 ──
        models.TestCase(
            name="查询不存在的用户",
            directory_id=d_new.id,
            description="通过不存在的 user_id 调用查询接口，验证系统返回 404 及正确的错误信息。",
            priority=models.CasePriority.p0,
            tags=["用户模块", "异常路径"],
            status=models.StatusEnum.running,
            preconditions="接口服务已启动，测试数据库中不存在 id=99999 的用户",
            steps_manual=[
                {"seq": 1, "action": "发送 GET /api/users/99999", "expected": "HTTP 404"},
                {"seq": 2, "action": "检查响应体 detail 字段", "expected": "包含 'User not found'"},
            ],
            expected_result="返回 404，响应体包含 detail 字段说明用户不存在。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 8, 7, 23, 34, 16),
            updated_at=datetime(2021, 8, 7, 23, 34, 16),
        ),
        models.TestCase(
            name="查询存在的用户",
            directory_id=d_new.id,
            description="通过已知存在的 user_id 查询，验证返回数据结构与字段值正确。",
            priority=models.CasePriority.p0,
            tags=["用户模块", "正常路径"],
            status=models.StatusEnum.running,
            preconditions="测试数据库中存在 id=1 的用户 testuser",
            steps_manual=[
                {"seq": 1, "action": "发送 GET /api/users/1", "expected": "HTTP 200"},
                {"seq": 2, "action": "校验响应字段 id、name、email", "expected": "字段值与预期一致"},
            ],
            expected_result="返回 200，响应体包含 id=1 用户的完整信息。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 8, 7, 23, 34, 16),
            updated_at=datetime(2021, 8, 7, 23, 34, 16),
        ),
        models.TestCase(
            name="查询所有用户列表",
            directory_id=d_new.id,
            description="分页查询用户列表，验证 total / page / items 结构正确，默认排序为创建时间倒序。",
            priority=models.CasePriority.p0,
            tags=["用户模块", "分页"],
            status=models.StatusEnum.running,
            preconditions="数据库中至少存在 3 条用户记录",
            steps_manual=[
                {"seq": 1, "action": "发送 GET /api/users?page=1&page_size=10", "expected": "HTTP 200"},
                {"seq": 2, "action": "校验 total >= 3", "expected": "total 字段值 >= 3"},
                {"seq": 3, "action": "校验 items 数组长度 <= page_size", "expected": "items.length <= 10"},
            ],
            expected_result="返回分页数据结构，items 不为空且字段完整。",
            is_automated=False,
            created_by="有故哥",
            created_at=datetime(2021, 8, 16, 23, 27, 44),
            updated_at=datetime(2021, 8, 16, 23, 27, 44),
        ),
        models.TestCase(
            name="正常用户登录",
            directory_id=d_new.id,
            description="使用正确的用户名和密码完成登录，验证返回 token 及过期时间符合预期。",
            priority=models.CasePriority.p0,
            tags=["登录", "冒烟测试"],
            status=models.StatusEnum.debug,
            preconditions="账号 testuser / Test123456 已在数据库中存在且未被禁用",
            steps_manual=[
                {"seq": 1, "action": "POST /api/auth/login，body: {username, password}", "expected": "HTTP 200"},
                {"seq": 2, "action": "检查响应体包含 access_token 字段", "expected": "token 非空字符串"},
                {"seq": 3, "action": "检查 expires_in 字段", "expected": "值为 86400（秒）"},
            ],
            expected_result="登录成功，返回有效 JWT token，过期时间 24h。",
            is_automated=True,
            version=2,
            created_by="有故哥",
            created_at=datetime(2021, 8, 1, 17, 33, 26),
            updated_at=datetime(2021, 8, 1, 17, 33, 26),
        ),
        models.TestCase(
            name="错误密码登录拦截",
            directory_id=d_new.id,
            description="使用错误密码登录，验证系统返回 401 且不泄露用户是否存在的信息。",
            priority=models.CasePriority.p1,
            tags=["登录", "安全"],
            status=models.StatusEnum.running,
            preconditions="账号 testuser 存在",
            steps_manual=[
                {"seq": 1, "action": "POST /api/auth/login，body: {username: testuser, password: wrong}", "expected": "HTTP 401"},
                {"seq": 2, "action": "检查响应体 detail 字段", "expected": "包含通用错误提示，不含具体原因"},
            ],
            expected_result="返回 401，响应体为统一的认证失败提示。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 8, 2, 10, 0, 0),
            updated_at=datetime(2021, 8, 2, 10, 0, 0),
        ),
        models.TestCase(
            name="Token 过期后访问受保护接口",
            directory_id=d_new.id,
            description="使用已过期的 JWT token 请求受保护资源，验证系统拒绝并提示重新登录。",
            priority=models.CasePriority.p1,
            tags=["登录", "安全", "Token"],
            status=models.StatusEnum.running,
            preconditions="持有一个已过期的 JWT token",
            steps_manual=[
                {"seq": 1, "action": "在 Authorization 头中携带过期 token 请求 GET /api/me", "expected": "HTTP 401"},
                {"seq": 2, "action": "检查响应 detail", "expected": "包含 'token expired' 或 'Unauthorized'"},
            ],
            expected_result="返回 401，body 提示 token 失效。",
            is_automated=False,
            created_by="有故哥",
            created_at=datetime(2021, 8, 3, 9, 15, 0),
            updated_at=datetime(2021, 8, 3, 9, 15, 0),
        ),
        # ── 新增 14 条 ──
        models.TestCase(
            name="创建用户成功",
            directory_id=d_new.id,
            description="使用合法参数调用创建用户接口，验证返回 201 及新用户数据完整。",
            priority=models.CasePriority.p0,
            tags=["用户模块", "正常路径"],
            status=models.StatusEnum.running,
            preconditions="邮箱 newuser@test.com 未被注册",
            steps_manual=[
                {"seq": 1, "action": "POST /api/users，body: {name, email, password}", "expected": "HTTP 201"},
                {"seq": 2, "action": "校验响应体包含 id、name、email", "expected": "字段值与请求一致"},
                {"seq": 3, "action": "GET /api/users/{id} 查询新用户", "expected": "HTTP 200，数据一致"},
            ],
            expected_result="用户创建成功，可通过查询接口取到完整数据。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 9, 1, 10, 0, 0),
            updated_at=datetime(2021, 9, 1, 10, 0, 0),
        ),
        models.TestCase(
            name="重复邮箱注册拦截",
            directory_id=d_new.id,
            description="使用已注册的邮箱再次发起注册，验证系统返回 409 Conflict。",
            priority=models.CasePriority.p1,
            tags=["用户模块", "异常路径"],
            status=models.StatusEnum.running,
            preconditions="邮箱 exist@test.com 已在系统中注册",
            steps_manual=[
                {"seq": 1, "action": "POST /api/users，body: {email: exist@test.com, ...}", "expected": "HTTP 409"},
                {"seq": 2, "action": "检查 detail 字段", "expected": "包含 'email already exists'"},
            ],
            expected_result="返回 409，提示邮箱已被占用。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 9, 2, 11, 0, 0),
            updated_at=datetime(2021, 9, 2, 11, 0, 0),
        ),
        models.TestCase(
            name="修改用户昵称",
            directory_id=d_new.id,
            description="已登录用户通过 PATCH 接口修改昵称，验证修改成功且 updated_at 更新。",
            priority=models.CasePriority.p2,
            tags=["用户模块", "更新"],
            status=models.StatusEnum.running,
            preconditions="用户 id=1 已登录，持有有效 token",
            steps_manual=[
                {"seq": 1, "action": "PATCH /api/users/1，body: {name: '新昵称'}", "expected": "HTTP 200"},
                {"seq": 2, "action": "检查响应 name 字段", "expected": "值为 '新昵称'"},
                {"seq": 3, "action": "检查 updated_at", "expected": "大于修改前的时间戳"},
            ],
            expected_result="昵称修改成功，updated_at 已刷新。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 9, 3, 14, 0, 0),
            updated_at=datetime(2021, 9, 3, 14, 0, 0),
        ),
        models.TestCase(
            name="删除用户后查询返回 404",
            directory_id=d_new.id,
            description="软删除用户后，通过查询接口确认已无法取到该用户数据。",
            priority=models.CasePriority.p1,
            tags=["用户模块", "软删除"],
            status=models.StatusEnum.running,
            preconditions="存在 id=100 的测试用户",
            steps_manual=[
                {"seq": 1, "action": "DELETE /api/users/100", "expected": "HTTP 204"},
                {"seq": 2, "action": "GET /api/users/100", "expected": "HTTP 404"},
                {"seq": 3, "action": "GET /api/users?include_deleted=true", "expected": "id=100 用户出现在列表中"},
            ],
            expected_result="删除后普通查询返回 404，带参数可查到已删除记录。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 9, 4, 9, 0, 0),
            updated_at=datetime(2021, 9, 4, 9, 0, 0),
        ),
        models.TestCase(
            name="用户密码修改后原 Token 失效",
            directory_id=d_new.id,
            description="用户修改密码后，旧 token 应立即失效，需重新登录获取新 token。",
            priority=models.CasePriority.p0,
            tags=["登录", "安全", "密码"],
            status=models.StatusEnum.running,
            preconditions="用户已登录，持有有效 token",
            steps_manual=[
                {"seq": 1, "action": "POST /api/users/1/change-password，body: {old, new}", "expected": "HTTP 200"},
                {"seq": 2, "action": "使用旧 token 请求 GET /api/me", "expected": "HTTP 401"},
                {"seq": 3, "action": "使用新密码重新登录", "expected": "HTTP 200，获得新 token"},
            ],
            expected_result="旧 token 立即失效，新密码登录成功。",
            is_automated=True,
            created_by="安全组",
            created_at=datetime(2021, 9, 5, 10, 0, 0),
            updated_at=datetime(2021, 9, 5, 10, 0, 0),
        ),
        models.TestCase(
            name="账号被禁用后登录拦截",
            directory_id=d_new.id,
            description="管理员禁用账号后，该账号登录时应返回 403 并提示账号已被禁用。",
            priority=models.CasePriority.p1,
            tags=["登录", "账号管理"],
            status=models.StatusEnum.running,
            preconditions="账号 banned@test.com 已被管理员设为禁用状态",
            steps_manual=[
                {"seq": 1, "action": "POST /api/auth/login，body: {email: banned@test.com, password}", "expected": "HTTP 403"},
                {"seq": 2, "action": "检查 detail 字段", "expected": "包含 '账号已被禁用'"},
            ],
            expected_result="返回 403，提示账号禁用，不返回 token。",
            is_automated=True,
            created_by="安全组",
            created_at=datetime(2021, 9, 6, 11, 0, 0),
            updated_at=datetime(2021, 9, 6, 11, 0, 0),
        ),
        models.TestCase(
            name="并发创建用户幂等性",
            directory_id=d_new.id,
            description="同时发起 10 个创建同邮箱用户的请求，验证最终数据库中只有 1 条记录。",
            priority=models.CasePriority.p2,
            tags=["用户模块", "并发", "幂等"],
            status=models.StatusEnum.debug,
            preconditions="邮箱 concurrent@test.com 未注册",
            steps_manual=[
                {"seq": 1, "action": "并发发起 10 个 POST /api/users 请求（相同邮箱）", "expected": "只有 1 个返回 201，其余 409"},
                {"seq": 2, "action": "查询数据库中该邮箱记录数", "expected": "count = 1"},
            ],
            expected_result="并发下只创建 1 条记录，无重复数据。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 9, 7, 15, 0, 0),
            updated_at=datetime(2021, 9, 7, 15, 0, 0),
        ),
        models.TestCase(
            name="用户名超长字段校验",
            directory_id=d_new.id,
            description="传入超过 128 字符的用户名，验证系统返回 422 Unprocessable Entity。",
            priority=models.CasePriority.p3,
            tags=["用户模块", "参数校验"],
            status=models.StatusEnum.running,
            preconditions="接口正常运行",
            steps_manual=[
                {"seq": 1, "action": "POST /api/users，body: {name: 'a'*200, email, password}", "expected": "HTTP 422"},
                {"seq": 2, "action": "检查 detail 中的字段错误", "expected": "包含 name 字段长度限制提示"},
            ],
            expected_result="返回 422，明确指出 name 字段超长。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 9, 8, 9, 0, 0),
            updated_at=datetime(2021, 9, 8, 9, 0, 0),
        ),
        models.TestCase(
            name="未认证请求受保护资源返回 401",
            directory_id=d_new.id,
            description="不携带任何 token 直接请求需要认证的接口，验证返回 401。",
            priority=models.CasePriority.p0,
            tags=["安全", "认证"],
            status=models.StatusEnum.running,
            preconditions="接口正常运行",
            steps_manual=[
                {"seq": 1, "action": "不带 Authorization 头请求 GET /api/me", "expected": "HTTP 401"},
            ],
            expected_result="返回 401 Unauthorized。",
            is_automated=True,
            created_by="安全组",
            created_at=datetime(2021, 9, 9, 10, 0, 0),
            updated_at=datetime(2021, 9, 9, 10, 0, 0),
        ),
        models.TestCase(
            name="刷新 Token 获取新 Access Token",
            directory_id=d_new.id,
            description="使用有效 refresh_token 调用刷新接口，验证返回新的 access_token。",
            priority=models.CasePriority.p1,
            tags=["登录", "Token"],
            status=models.StatusEnum.running,
            preconditions="持有有效的 refresh_token",
            steps_manual=[
                {"seq": 1, "action": "POST /api/auth/refresh，body: {refresh_token}", "expected": "HTTP 200"},
                {"seq": 2, "action": "检查响应包含新 access_token", "expected": "token 与原 access_token 不同"},
            ],
            expected_result="成功获取新 access_token，旧 token 仍在过期前有效。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 9, 10, 11, 0, 0),
            updated_at=datetime(2021, 9, 10, 11, 0, 0),
        ),
        models.TestCase(
            name="用户列表关键字搜索",
            directory_id=d_new.id,
            description="通过 keyword 参数过滤用户列表，验证只返回 name 包含关键字的记录。",
            priority=models.CasePriority.p2,
            tags=["用户模块", "搜索"],
            status=models.StatusEnum.running,
            preconditions="数据库中存在 name 含 '张' 的用户至少 2 条",
            steps_manual=[
                {"seq": 1, "action": "GET /api/users?keyword=张", "expected": "HTTP 200"},
                {"seq": 2, "action": "校验所有 items 的 name 包含 '张'", "expected": "全部满足条件"},
            ],
            expected_result="仅返回 name 含 '张' 的用户。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 9, 11, 14, 0, 0),
            updated_at=datetime(2021, 9, 11, 14, 0, 0),
        ),
        models.TestCase(
            name="邮箱格式校验拦截",
            directory_id=d_new.id,
            description="传入非法邮箱格式，验证系统返回 422 并指明 email 字段错误。",
            priority=models.CasePriority.p2,
            tags=["用户模块", "参数校验"],
            status=models.StatusEnum.running,
            preconditions="接口正常运行",
            steps_manual=[
                {"seq": 1, "action": "POST /api/users，body: {email: 'not-an-email', ...}", "expected": "HTTP 422"},
                {"seq": 2, "action": "检查 detail[0].loc 包含 email", "expected": "字段定位到 email"},
            ],
            expected_result="返回 422，明确指出 email 格式非法。",
            is_automated=True,
            created_by="有故哥",
            created_at=datetime(2021, 9, 12, 9, 0, 0),
            updated_at=datetime(2021, 9, 12, 9, 0, 0),
        ),
        models.TestCase(
            name="退出登录后 Token 失效",
            directory_id=d_new.id,
            description="调用退出接口后，该 access_token 加入黑名单，后续请求返回 401。",
            priority=models.CasePriority.p1,
            tags=["登录", "安全"],
            status=models.StatusEnum.running,
            preconditions="用户已登录，持有有效 token",
            steps_manual=[
                {"seq": 1, "action": "POST /api/auth/logout，携带 token", "expected": "HTTP 200"},
                {"seq": 2, "action": "使用相同 token 请求 GET /api/me", "expected": "HTTP 401"},
            ],
            expected_result="退出后 token 立即失效，无法再访问受保护资源。",
            is_automated=True,
            created_by="安全组",
            created_at=datetime(2021, 9, 13, 16, 0, 0),
            updated_at=datetime(2021, 9, 13, 16, 0, 0),
        ),
        models.TestCase(
            name="管理员批量禁用用户",
            directory_id=d_new.id,
            description="管理员通过批量接口一次禁用多个用户，验证全部用户状态更新且不影响其他用户。",
            priority=models.CasePriority.p2,
            tags=["用户模块", "批量操作", "管理员"],
            status=models.StatusEnum.debug,
            preconditions="存在 id=[2,3,4] 的活跃用户，管理员已登录",
            steps_manual=[
                {"seq": 1, "action": "POST /api/admin/users/batch-disable，body: {ids: [2,3,4]}", "expected": "HTTP 200"},
                {"seq": 2, "action": "分别查询用户 2/3/4", "expected": "status 均为 disabled"},
                {"seq": 3, "action": "查询用户 1（未在列表中）", "expected": "status 未变化"},
            ],
            expected_result="指定用户全部禁用，其余用户不受影响。",
            is_automated=True,
            created_by="管理组",
            created_at=datetime(2021, 9, 14, 11, 0, 0),
            updated_at=datetime(2021, 9, 14, 11, 0, 0),
        ),
    ])

    d_log = models.CaseDirectory(name="发个日文联报", path="发个日文联报", group_id=g_test.id, sort_order=1)
    db.add(d_log)
    db.flush()

    db.add_all([
        # ── 原有 2 条 ──
        models.TestCase(
            name="日志级别动态切换",
            directory_id=d_log.id,
            description="通过管理接口将日志级别从 INFO 切换到 DEBUG，验证后续日志输出包含 DEBUG 信息。",
            priority=models.CasePriority.p2,
            tags=["日志", "运维"],
            status=models.StatusEnum.running,
            preconditions="服务已启动，当前日志级别为 INFO",
            steps_manual=[
                {"seq": 1, "action": "POST /admin/log-level {level: DEBUG}", "expected": "HTTP 200"},
                {"seq": 2, "action": "触发一次 DEBUG 日志行为", "expected": "日志文件中出现 [DEBUG] 行"},
            ],
            expected_result="切换成功，后续日志包含 DEBUG 级别条目。",
            is_automated=False,
            created_by="运维组",
            created_at=datetime(2022, 3, 10, 9, 0, 0),
            updated_at=datetime(2022, 3, 10, 9, 0, 0),
        ),
        models.TestCase(
            name="审计日志完整性校验",
            directory_id=d_log.id,
            description="执行一系列写操作后，校验审计日志记录条数、操作类型及操作人与实际行为完全一致。",
            priority=models.CasePriority.p1,
            tags=["日志", "审计", "合规"],
            status=models.StatusEnum.running,
            preconditions="审计日志服务已启用，测试用户已登录",
            steps_manual=[
                {"seq": 1, "action": "依次执行创建、修改、删除操作各一次", "expected": "操作成功"},
                {"seq": 2, "action": "查询审计日志 GET /audit?limit=10", "expected": "返回最近 3 条日志"},
                {"seq": 3, "action": "比对日志中的 action / user / timestamp", "expected": "与实际操作一一对应"},
            ],
            expected_result="审计日志条数为 3，内容与操作完全吻合。",
            is_automated=True,
            created_by="运维组",
            created_at=datetime(2022, 3, 15, 14, 30, 0),
            updated_at=datetime(2022, 3, 15, 14, 30, 0),
        ),
        # ── 新增 6 条 ──
        models.TestCase(
            name="错误日志告警触发",
            directory_id=d_log.id,
            description="连续出现 5 次 ERROR 日志时，系统应自动触发告警通知到企微群。",
            priority=models.CasePriority.p1,
            tags=["日志", "告警", "监控"],
            status=models.StatusEnum.running,
            preconditions="告警规则已配置：5 分钟内 ERROR 数 >= 5 触发告警；企微 webhook 已配置",
            steps_manual=[
                {"seq": 1, "action": "在 5 分钟内触发 5 次 ERROR 日志", "expected": "系统记录到阈值"},
                {"seq": 2, "action": "检查企微群消息", "expected": "收到告警通知，包含错误摘要"},
            ],
            expected_result="告警准时触发，企微消息内容包含服务名、错误级别、时间。",
            is_automated=False,
            created_by="运维组",
            created_at=datetime(2022, 4, 1, 10, 0, 0),
            updated_at=datetime(2022, 4, 1, 10, 0, 0),
        ),
        models.TestCase(
            name="日志文件自动归档轮转",
            directory_id=d_log.id,
            description="单个日志文件超过 100MB 时，系统自动归档压缩并创建新日志文件，不丢失数据。",
            priority=models.CasePriority.p2,
            tags=["日志", "运维", "存储"],
            status=models.StatusEnum.running,
            preconditions="日志轮转策略已配置：max_size=100MB",
            steps_manual=[
                {"seq": 1, "action": "将日志文件填充至 100MB 以上", "expected": "触发轮转机制"},
                {"seq": 2, "action": "检查旧日志文件", "expected": "已压缩为 .gz 格式"},
                {"seq": 3, "action": "检查新日志文件", "expected": "大小 < 1KB，继续正常写入"},
            ],
            expected_result="轮转成功，无日志丢失，旧文件已压缩。",
            is_automated=True,
            created_by="运维组",
            created_at=datetime(2022, 4, 5, 14, 0, 0),
            updated_at=datetime(2022, 4, 5, 14, 0, 0),
        ),
        models.TestCase(
            name="结构化日志字段完整性",
            directory_id=d_log.id,
            description="业务请求日志应包含 trace_id / user_id / latency_ms / status_code 等标准字段。",
            priority=models.CasePriority.p1,
            tags=["日志", "规范"],
            status=models.StatusEnum.running,
            preconditions="服务已部署，日志格式为 JSON",
            steps_manual=[
                {"seq": 1, "action": "发起一次正常业务请求", "expected": "请求成功"},
                {"seq": 2, "action": "查看对应请求日志条目", "expected": "包含 trace_id、user_id、latency_ms、status_code"},
            ],
            expected_result="所有必填字段存在且值合理（latency > 0，status_code = 200）。",
            is_automated=True,
            created_by="平台组",
            created_at=datetime(2022, 4, 8, 9, 0, 0),
            updated_at=datetime(2022, 4, 8, 9, 0, 0),
        ),
        models.TestCase(
            name="慢请求日志采样率验证",
            directory_id=d_log.id,
            description="响应时间超过 500ms 的请求必须 100% 记录慢日志，低于阈值的采样率为 10%。",
            priority=models.CasePriority.p2,
            tags=["日志", "性能", "采样"],
            status=models.StatusEnum.debug,
            preconditions="慢请求采样配置已生效",
            steps_manual=[
                {"seq": 1, "action": "发送 20 个耗时 > 500ms 的请求", "expected": "全部出现在慢日志中（20 条）"},
                {"seq": 2, "action": "发送 100 个耗时 < 500ms 的请求", "expected": "慢日志中约出现 10 条（±3）"},
            ],
            expected_result="慢请求 100% 采集，快请求约 10% 采集。",
            is_automated=True,
            created_by="平台组",
            created_at=datetime(2022, 4, 10, 11, 0, 0),
            updated_at=datetime(2022, 4, 10, 11, 0, 0),
        ),
        models.TestCase(
            name="日志链路追踪 trace_id 透传",
            directory_id=d_log.id,
            description="请求携带 X-Trace-Id 请求头时，该 trace_id 应透传到所有下游服务日志中。",
            priority=models.CasePriority.p1,
            tags=["日志", "链路追踪", "微服务"],
            status=models.StatusEnum.running,
            preconditions="微服务 A、B、C 均已部署并集成链路追踪中间件",
            steps_manual=[
                {"seq": 1, "action": "携带 X-Trace-Id: test-trace-001 请求服务 A", "expected": "HTTP 200"},
                {"seq": 2, "action": "查询服务 A/B/C 的日志，过滤 trace_id=test-trace-001", "expected": "三个服务均有该 trace_id 的日志"},
            ],
            expected_result="trace_id 贯穿全链路，可通过一个 trace_id 串联所有服务日志。",
            is_automated=True,
            created_by="平台组",
            created_at=datetime(2022, 4, 12, 15, 0, 0),
            updated_at=datetime(2022, 4, 12, 15, 0, 0),
        ),
        models.TestCase(
            name="敏感信息日志脱敏",
            directory_id=d_log.id,
            description="包含手机号、身份证号、密码的请求参数在日志中应自动脱敏，不得明文记录。",
            priority=models.CasePriority.p0,
            tags=["日志", "安全", "脱敏"],
            status=models.StatusEnum.running,
            preconditions="脱敏规则已配置：手机号保留前 3 后 4，密码全掩码",
            steps_manual=[
                {"seq": 1, "action": "发起含手机号 13812345678 的请求", "expected": "请求成功"},
                {"seq": 2, "action": "查看请求日志", "expected": "日志中手机号显示为 138****5678"},
                {"seq": 3, "action": "查看含密码参数的日志", "expected": "密码字段显示为 ******"},
            ],
            expected_result="敏感字段全部脱敏，无明文泄露。",
            is_automated=True,
            created_by="安全组",
            created_at=datetime(2022, 4, 15, 10, 0, 0),
            updated_at=datetime(2022, 4, 15, 10, 0, 0),
        ),
    ])

    d_misc = models.CaseDirectory(name="好的无故事", path="好的无故事", group_id=g_test.id, sort_order=2)
    db.add(d_misc)
    db.flush()

    db.add_all([
        models.TestCase(
            name="健康检查接口响应时间",
            directory_id=d_misc.id,
            description="/health 接口响应时间应在 50ms 以内，且返回正确状态。",
            priority=models.CasePriority.p0,
            tags=["运维", "性能", "冒烟测试"],
            status=models.StatusEnum.running,
            preconditions="服务已启动",
            steps_manual=[
                {"seq": 1, "action": "GET /health", "expected": "HTTP 200"},
                {"seq": 2, "action": "记录响应时间", "expected": "< 50ms"},
                {"seq": 3, "action": "检查响应体", "expected": "{status: ok}"},
            ],
            expected_result="响应时间 < 50ms，状态为 ok。",
            is_automated=True,
            created_by="运维组",
            created_at=datetime(2022, 5, 1, 9, 0, 0),
            updated_at=datetime(2022, 5, 1, 9, 0, 0),
        ),
        models.TestCase(
            name="API 版本号正确返回",
            directory_id=d_misc.id,
            description="GET /version 接口返回当前部署版本号，与 CI/CD 注入的环境变量一致。",
            priority=models.CasePriority.p3,
            tags=["运维", "版本"],
            status=models.StatusEnum.running,
            preconditions="CI 已在构建时注入 APP_VERSION 环境变量",
            steps_manual=[
                {"seq": 1, "action": "GET /version", "expected": "HTTP 200"},
                {"seq": 2, "action": "比对 version 字段与 APP_VERSION 环境变量", "expected": "完全一致"},
            ],
            expected_result="版本号与环境变量一致。",
            is_automated=True,
            created_by="运维组",
            created_at=datetime(2022, 5, 3, 10, 0, 0),
            updated_at=datetime(2022, 5, 3, 10, 0, 0),
        ),
        models.TestCase(
            name="数据库连接池耗尽恢复",
            directory_id=d_misc.id,
            description="模拟连接池耗尽，验证系统返回 503 并在连接释放后自动恢复，不需要重启。",
            priority=models.CasePriority.p1,
            tags=["稳定性", "数据库", "容灾"],
            status=models.StatusEnum.debug,
            preconditions="连接池 max_size=5，已有 5 个长连接占用",
            steps_manual=[
                {"seq": 1, "action": "发起第 6 个需要 DB 的请求", "expected": "HTTP 503 或等待超时"},
                {"seq": 2, "action": "释放一个旧连接", "expected": "待处理请求自动获得连接并成功响应"},
            ],
            expected_result="连接池耗尽时 503，释放后自动恢复，无需重启。",
            is_automated=False,
            created_by="平台组",
            created_at=datetime(2022, 5, 5, 14, 0, 0),
            updated_at=datetime(2022, 5, 5, 14, 0, 0),
        ),
        models.TestCase(
            name="CORS 预检请求处理",
            directory_id=d_misc.id,
            description="浏览器跨域 OPTIONS 预检请求，验证响应头包含正确的 Access-Control-Allow-* 字段。",
            priority=models.CasePriority.p2,
            tags=["CORS", "安全"],
            status=models.StatusEnum.running,
            preconditions="服务已配置 CORS 允许 localhost:5173",
            steps_manual=[
                {"seq": 1, "action": "OPTIONS /api/users，携带 Origin: http://localhost:5173", "expected": "HTTP 200"},
                {"seq": 2, "action": "检查 Access-Control-Allow-Origin 头", "expected": "http://localhost:5173"},
                {"seq": 3, "action": "检查 Access-Control-Allow-Methods 头", "expected": "包含 GET, POST, PATCH, DELETE"},
            ],
            expected_result="预检响应包含正确 CORS 头，浏览器允许跨域请求。",
            is_automated=True,
            created_by="平台组",
            created_at=datetime(2022, 5, 8, 9, 0, 0),
            updated_at=datetime(2022, 5, 8, 9, 0, 0),
        ),
        models.TestCase(
            name="请求体超出大小限制",
            directory_id=d_misc.id,
            description="上传超过 10MB 的请求体，验证服务器返回 413 Request Entity Too Large。",
            priority=models.CasePriority.p2,
            tags=["安全", "参数校验"],
            status=models.StatusEnum.running,
            preconditions="服务配置 max_request_body=10MB",
            steps_manual=[
                {"seq": 1, "action": "POST /api/upload，body 为 11MB 数据", "expected": "HTTP 413"},
            ],
            expected_result="返回 413，不处理超限请求体。",
            is_automated=True,
            created_by="平台组",
            created_at=datetime(2022, 5, 10, 11, 0, 0),
            updated_at=datetime(2022, 5, 10, 11, 0, 0),
        ),
        models.TestCase(
            name="接口限流触发后恢复",
            directory_id=d_misc.id,
            description="同一 IP 1 分钟内超过 100 次请求触发限流，等待 1 分钟后自动恢复正常访问。",
            priority=models.CasePriority.p1,
            tags=["限流", "安全"],
            status=models.StatusEnum.running,
            preconditions="限流规则：同 IP 100 次/分钟",
            steps_manual=[
                {"seq": 1, "action": "同一 IP 快速发送 101 个请求", "expected": "第 101 个返回 HTTP 429"},
                {"seq": 2, "action": "等待 60 秒后重新发送请求", "expected": "HTTP 200，正常访问"},
            ],
            expected_result="触发限流后返回 429，冷却后自动解除。",
            is_automated=True,
            created_by="安全组",
            created_at=datetime(2022, 5, 12, 14, 0, 0),
            updated_at=datetime(2022, 5, 12, 14, 0, 0),
        ),
        models.TestCase(
            name="服务优雅停机验证",
            directory_id=d_misc.id,
            description="发送 SIGTERM 信号后，服务应等待进行中的请求处理完毕再关闭，不强制中断。",
            priority=models.CasePriority.p1,
            tags=["运维", "稳定性"],
            status=models.StatusEnum.disabled,
            preconditions="服务已配置 graceful_shutdown_timeout=30s",
            steps_manual=[
                {"seq": 1, "action": "触发一个耗时 10s 的长请求", "expected": "请求开始处理"},
                {"seq": 2, "action": "在请求进行中发送 SIGTERM", "expected": "服务不立即退出，继续处理请求"},
                {"seq": 3, "action": "等待请求完成", "expected": "请求正常响应后服务退出"},
            ],
            expected_result="优雅停机，进行中请求完整响应，不丢失数据。",
            is_automated=False,
            created_by="运维组",
            created_at=datetime(2022, 5, 15, 16, 0, 0),
            updated_at=datetime(2022, 5, 15, 16, 0, 0),
        ),
    ])

    # ════════════════════════════════════════════════════════
    # 客服服务组
    # ════════════════════════════════════════════════════════
    d_routing = models.CaseDirectory(
        name="智能分流", path="智能分流", group_id=g_support.id, sort_order=0
    )
    db.add(d_routing)
    db.flush()

    db.add_all([
        # ── 原有 3 条 ──
        models.TestCase(
            name="高优先级客户直达专席",
            directory_id=d_routing.id,
            description="VIP 客户发起咨询时，系统自动识别等级并绕过普通队列直接分配专属客服。",
            priority=models.CasePriority.p1,
            tags=["分流", "VIP"],
            status=models.StatusEnum.running,
            preconditions="系统中存在 VIP 级别客户账号，专属客服坐席在线",
            steps_manual=[
                {"seq": 1, "action": "使用 VIP 账号发起咨询请求", "expected": "请求进入 VIP 队列"},
                {"seq": 2, "action": "等待分配完成", "expected": "分配耗时 < 5s，坐席为专属坐席"},
            ],
            expected_result="VIP 客户在 5 秒内分配到专属坐席，不经过普通排队。",
            is_automated=True,
            created_by="客服中心",
            created_at=datetime(2026, 4, 27, 21, 10, 3),
            updated_at=datetime(2026, 4, 27, 21, 10, 3),
        ),
        models.TestCase(
            name="普通客户排队等待超时自动回调",
            directory_id=d_routing.id,
            description="普通客户排队超过设定阈值（3 分钟）时，系统自动触发回调通知。",
            priority=models.CasePriority.p2,
            tags=["分流", "超时", "回调"],
            status=models.StatusEnum.running,
            preconditions="所有坐席繁忙，普通客户已进入等待队列",
            steps_manual=[
                {"seq": 1, "action": "模拟客户排队等待 3 分钟以上", "expected": "系统触发超时检测"},
                {"seq": 2, "action": "检查回调通知是否发送", "expected": "客户收到短信/App 推送提示稍后回电"},
            ],
            expected_result="等待超过阈值后，系统主动推送回调通知，客户体验不低于预期。",
            is_automated=False,
            created_by="客服中心",
            created_at=datetime(2026, 4, 28, 10, 0, 0),
            updated_at=datetime(2026, 4, 28, 10, 0, 0),
        ),
        models.TestCase(
            name="意图识别准确率基准测试",
            directory_id=d_routing.id,
            description="向智能分流引擎输入 50 条预设咨询语句，验证意图分类准确率不低于 90%。",
            priority=models.CasePriority.p0,
            tags=["分流", "NLP", "基准"],
            status=models.StatusEnum.debug,
            preconditions="已准备 50 条带标注的测试语句；NLP 模型已部署",
            steps_manual=[
                {"seq": 1, "action": "批量发送 50 条测试语句到意图识别接口", "expected": "全部返回 200"},
                {"seq": 2, "action": "比对返回意图与标注值", "expected": "正确数 >= 45"},
            ],
            expected_result="准确率 >= 90%，未达标输出差异清单。",
            is_automated=True,
            created_by="AI 团队",
            created_at=datetime(2026, 4, 20, 15, 0, 0),
            updated_at=datetime(2026, 4, 28, 9, 30, 0),
            version=3,
        ),
        # ── 新增 5 条 ──
        models.TestCase(
            name="坐席技能标签匹配分流",
            directory_id=d_routing.id,
            description="客户咨询特定问题类型（如退款）时，系统优先分配持有对应技能标签的坐席。",
            priority=models.CasePriority.p1,
            tags=["分流", "技能匹配"],
            status=models.StatusEnum.running,
            preconditions="坐席 A 拥有技能标签【退款处理】，坐席 B 仅有【普通咨询】",
            steps_manual=[
                {"seq": 1, "action": "客户输入退款相关咨询", "expected": "系统识别意图为【退款】"},
                {"seq": 2, "action": "查看分配结果", "expected": "分配给坐席 A（持有退款技能）"},
            ],
            expected_result="优先按技能标签分配，无匹配时降级到普通坐席。",
            is_automated=True,
            created_by="客服中心",
            created_at=datetime(2026, 4, 29, 9, 0, 0),
            updated_at=datetime(2026, 4, 29, 9, 0, 0),
        ),
        models.TestCase(
            name="全部坐席离线时排队兜底",
            directory_id=d_routing.id,
            description="当所有坐席均不在线时，新咨询应进入离线排队，坐席上线后自动分配。",
            priority=models.CasePriority.p1,
            tags=["分流", "兜底", "容灾"],
            status=models.StatusEnum.running,
            preconditions="所有坐席均已下线",
            steps_manual=[
                {"seq": 1, "action": "发起咨询请求", "expected": "系统提示'当前无坐席在线，已为您排队'"},
                {"seq": 2, "action": "坐席 A 上线", "expected": "自动将排队中的咨询分配给坐席 A"},
            ],
            expected_result="离线排队功能正常，坐席上线后 10 秒内完成分配。",
            is_automated=False,
            created_by="客服中心",
            created_at=datetime(2026, 4, 29, 10, 0, 0),
            updated_at=datetime(2026, 4, 29, 10, 0, 0),
        ),
        models.TestCase(
            name="多轮对话上下文携带",
            directory_id=d_routing.id,
            description="用户在智能客服多轮对话中，后续问题能正确关联前文上下文，不丢失会话状态。",
            priority=models.CasePriority.p2,
            tags=["NLP", "多轮对话", "上下文"],
            status=models.StatusEnum.running,
            preconditions="智能客服已接入对话管理系统，session 超时设置为 30 分钟",
            steps_manual=[
                {"seq": 1, "action": "发送消息：'我想查询订单 123456'", "expected": "返回订单信息"},
                {"seq": 2, "action": "继续发送：'它的物流在哪'", "expected": "系统理解'它'指代订单 123456 并返回物流信息"},
            ],
            expected_result="多轮对话上下文正确关联，无需用户重复说明订单号。",
            is_automated=True,
            created_by="AI 团队",
            created_at=datetime(2026, 4, 29, 11, 0, 0),
            updated_at=datetime(2026, 4, 29, 11, 0, 0),
        ),
        models.TestCase(
            name="分流规则热更新不重启",
            directory_id=d_routing.id,
            description="通过管理后台更新分流规则后，新规则在 30 秒内生效，无需重启服务。",
            priority=models.CasePriority.p1,
            tags=["分流", "配置热更新"],
            status=models.StatusEnum.running,
            preconditions="分流规则管理后台已部署",
            steps_manual=[
                {"seq": 1, "action": "在管理后台修改分流规则（如调整优先级阈值）", "expected": "规则保存成功"},
                {"seq": 2, "action": "等待 30 秒后，触发新规则对应的咨询场景", "expected": "按新规则分流"},
            ],
            expected_result="规则在 30 秒内生效，服务无重启，在途请求不受影响。",
            is_automated=False,
            created_by="平台组",
            created_at=datetime(2026, 4, 29, 14, 0, 0),
            updated_at=datetime(2026, 4, 29, 14, 0, 0),
        ),
        models.TestCase(
            name="并发咨询分流压力测试",
            directory_id=d_routing.id,
            description="模拟 500 个并发咨询请求，验证分流系统在高并发下响应时间 P99 < 2 秒。",
            priority=models.CasePriority.p0,
            tags=["分流", "性能", "压测"],
            status=models.StatusEnum.debug,
            preconditions="压测环境已准备，坐席模拟器配置 100 个在线坐席",
            steps_manual=[
                {"seq": 1, "action": "使用压测工具发起 500 并发咨询", "expected": "无请求超时失败"},
                {"seq": 2, "action": "统计 P99 响应时间", "expected": "< 2000ms"},
                {"seq": 3, "action": "检查分配成功率", "expected": ">= 99%"},
            ],
            expected_result="P99 延迟 < 2s，分配成功率 >= 99%。",
            is_automated=True,
            created_by="性能组",
            created_at=datetime(2026, 4, 29, 15, 0, 0),
            updated_at=datetime(2026, 4, 29, 15, 0, 0),
        ),
    ])

    d_vip = models.CaseDirectory(
        name="VIP 专线", path="VIP 专线", group_id=g_support.id, sort_order=1
    )
    db.add(d_vip)
    db.flush()

    db.add_all([
        # ── 原有 2 条 ──
        models.TestCase(
            name="VIP 专线接通率统计",
            directory_id=d_vip.id,
            description="统计 VIP 专线在高峰时段（10:00–12:00）的接通率，目标 >= 99%。",
            priority=models.CasePriority.p1,
            tags=["VIP", "统计", "SLA"],
            status=models.StatusEnum.running,
            preconditions="已有高峰时段历史通话数据",
            steps_manual=[
                {"seq": 1, "action": "查询 GET /reports/vip-line?period=peak", "expected": "HTTP 200"},
                {"seq": 2, "action": "检查 connect_rate 字段", "expected": ">= 0.99"},
            ],
            expected_result="接通率字段 >= 0.99，否则触发告警。",
            is_automated=True,
            created_by="质量组",
            created_at=datetime(2026, 4, 25, 11, 0, 0),
            updated_at=datetime(2026, 4, 25, 11, 0, 0),
        ),
        models.TestCase(
            name="专线坐席强制下线恢复",
            directory_id=d_vip.id,
            description="坐席网络断连后，系统自动将进行中的通话转移给其他在线坐席，客户无感知。",
            priority=models.CasePriority.p0,
            tags=["VIP", "容灾", "坐席"],
            status=models.StatusEnum.running,
            preconditions="VIP 坐席 A 正在服务客户；坐席 B 空闲在线",
            steps_manual=[
                {"seq": 1, "action": "模拟坐席 A 网络断线", "expected": "系统检测到坐席离线"},
                {"seq": 2, "action": "等待自动转移", "expected": "通话在 10s 内转接到坐席 B"},
                {"seq": 3, "action": "客户侧感知检查", "expected": "等待音 < 3s，无电话中断"},
            ],
            expected_result="通话无缝转移，客户等待时间 < 3 秒。",
            is_automated=False,
            created_by="质量组",
            created_at=datetime(2026, 4, 26, 16, 0, 0),
            updated_at=datetime(2026, 4, 26, 16, 0, 0),
        ),
        # ── 新增 4 条 ──
        models.TestCase(
            name="VIP 客户身份识别精度",
            directory_id=d_vip.id,
            description="系统通过手机号自动识别来电客户 VIP 等级，识别准确率 >= 99.5%。",
            priority=models.CasePriority.p0,
            tags=["VIP", "身份识别"],
            status=models.StatusEnum.running,
            preconditions="VIP 数据库已与通话系统集成，测试集包含 200 条已知数据",
            steps_manual=[
                {"seq": 1, "action": "用 200 个测试号码模拟来电", "expected": "系统返回对应等级"},
                {"seq": 2, "action": "比对识别结果与预期", "expected": "正确数 >= 199"},
            ],
            expected_result="识别准确率 >= 99.5%。",
            is_automated=True,
            created_by="质量组",
            created_at=datetime(2026, 4, 27, 9, 0, 0),
            updated_at=datetime(2026, 4, 27, 9, 0, 0),
        ),
        models.TestCase(
            name="VIP 通话录音自动归档",
            directory_id=d_vip.id,
            description="VIP 通话结束后，录音文件应在 5 分钟内自动上传至对象存储并生成可访问链接。",
            priority=models.CasePriority.p1,
            tags=["VIP", "录音", "存储"],
            status=models.StatusEnum.running,
            preconditions="对象存储已配置，录音服务正常",
            steps_manual=[
                {"seq": 1, "action": "完成一次 VIP 通话并挂断", "expected": "通话结束事件触发"},
                {"seq": 2, "action": "等待 5 分钟后查询录音记录", "expected": "录音已上传，URL 可访问"},
            ],
            expected_result="录音 5 分钟内归档完成，URL 有效期 >= 7 天。",
            is_automated=False,
            created_by="质量组",
            created_at=datetime(2026, 4, 27, 11, 0, 0),
            updated_at=datetime(2026, 4, 27, 11, 0, 0),
        ),
        models.TestCase(
            name="VIP 满意度评分回收",
            directory_id=d_vip.id,
            description="通话结束后发送满意度短信，用户回复评分后系统正确入库并关联通话记录。",
            priority=models.CasePriority.p2,
            tags=["VIP", "满意度", "短信"],
            status=models.StatusEnum.running,
            preconditions="满意度评分短信模板已配置",
            steps_manual=[
                {"seq": 1, "action": "完成通话后检查短信发送状态", "expected": "短信已发送"},
                {"seq": 2, "action": "模拟用户回复数字'5'", "expected": "系统接收并解析为 5 分"},
                {"seq": 3, "action": "查询通话记录的评分字段", "expected": "score = 5"},
            ],
            expected_result="评分正确入库并与通话记录关联。",
            is_automated=True,
            created_by="质量组",
            created_at=datetime(2026, 4, 27, 14, 0, 0),
            updated_at=datetime(2026, 4, 27, 14, 0, 0),
        ),
        models.TestCase(
            name="VIP 专线最大等待时间告警",
            directory_id=d_vip.id,
            description="VIP 客户等待时间超过 60 秒时，自动触发主管告警并记录异常事件。",
            priority=models.CasePriority.p1,
            tags=["VIP", "SLA", "告警"],
            status=models.StatusEnum.running,
            preconditions="告警规则：VIP 等待 > 60s 触发；主管邮箱已配置",
            steps_manual=[
                {"seq": 1, "action": "VIP 客户进入等待队列", "expected": "开始计时"},
                {"seq": 2, "action": "模拟等待超过 60 秒未分配", "expected": "触发告警"},
                {"seq": 3, "action": "检查告警通知", "expected": "主管收到告警邮件，包含客户 ID 和等待时长"},
            ],
            expected_result="超时告警准时触发，通知内容完整。",
            is_automated=True,
            created_by="质量组",
            created_at=datetime(2026, 4, 27, 16, 0, 0),
            updated_at=datetime(2026, 4, 27, 16, 0, 0),
        ),
    ])

    # ════════════════════════════════════════════════════════
    # 运营增长组
    # ════════════════════════════════════════════════════════
    d_recall = models.CaseDirectory(
        name="召回触达", path="召回触达", group_id=g_ops.id, sort_order=0
    )
    db.add(d_recall)
    db.flush()

    db.add_all([
        # ── 原有 3 条 ──
        models.TestCase(
            name="沉默用户 Push 召回触发",
            directory_id=d_recall.id,
            description="超过 7 天未登录的用户在每日 20:00 收到 Push 消息，验证发送成功率与内容模板正确。",
            priority=models.CasePriority.p1,
            tags=["召回", "Push", "消息"],
            status=models.StatusEnum.running,
            preconditions="测试账号最后登录时间 > 7 天前；Push 渠道配置正常",
            steps_manual=[
                {"seq": 1, "action": "触发每日召回任务（手动或等待定时）", "expected": "任务执行成功"},
                {"seq": 2, "action": "查询发送日志", "expected": "测试账号在发送列表中"},
                {"seq": 3, "action": "检查 Push 内容", "expected": "标题/正文与模板一致，包含个性化昵称"},
            ],
            expected_result="Push 成功送达，内容含用户昵称，发送成功率 >= 95%。",
            is_automated=True,
            created_by="增长组",
            created_at=datetime(2026, 3, 1, 12, 0, 0),
            updated_at=datetime(2026, 4, 10, 8, 0, 0),
            version=2,
        ),
        models.TestCase(
            name="召回频控限制验证",
            directory_id=d_recall.id,
            description="同一用户在 24 小时内只触发一次召回，超出频控后不再发送。",
            priority=models.CasePriority.p2,
            tags=["召回", "频控"],
            status=models.StatusEnum.running,
            preconditions="用户已在今日 09:00 收到一次召回消息",
            steps_manual=[
                {"seq": 1, "action": "再次触发召回任务", "expected": "系统命中频控规则"},
                {"seq": 2, "action": "检查发送日志", "expected": "该用户本次未进入发送列表"},
            ],
            expected_result="用户在 24h 内不会重复收到召回消息。",
            is_automated=True,
            created_by="增长组",
            created_at=datetime(2026, 3, 5, 10, 0, 0),
            updated_at=datetime(2026, 3, 5, 10, 0, 0),
        ),
        models.TestCase(
            name="召回点击率数据回流",
            directory_id=d_recall.id,
            description="用户点击召回消息后，埋点事件正确上报，数据在 BI 系统 T+1 可见。",
            priority=models.CasePriority.p2,
            tags=["召回", "埋点", "BI"],
            status=models.StatusEnum.disabled,
            preconditions="埋点 SDK 已集成，BI 数据仓库同步链路正常",
            steps_manual=[
                {"seq": 1, "action": "点击召回 Push，跳转 App", "expected": "埋点事件 recall_click 上报"},
                {"seq": 2, "action": "次日查询 BI 报表", "expected": "recall_click 事件计数 +1"},
            ],
            expected_result="埋点准确，数据 T+1 在 BI 报表中可见。",
            is_automated=False,
            created_by="数据组",
            created_at=datetime(2026, 3, 10, 14, 0, 0),
            updated_at=datetime(2026, 3, 10, 14, 0, 0),
        ),
        # ── 新增 6 条 ──
        models.TestCase(
            name="召回消息 A/B 分组实验",
            directory_id=d_recall.id,
            description="对召回用户进行 50/50 分组，A 组发文案版本 1，B 组发版本 2，验证分组准确且数据隔离。",
            priority=models.CasePriority.p1,
            tags=["召回", "A/B 实验"],
            status=models.StatusEnum.running,
            preconditions="实验平台已创建 AB 实验，流量配置 50/50",
            steps_manual=[
                {"seq": 1, "action": "触发召回任务", "expected": "用户按 50/50 分配到两组"},
                {"seq": 2, "action": "查询 A 组用户收到的消息内容", "expected": "均为版本 1 文案"},
                {"seq": 3, "action": "查询 B 组用户收到的消息内容", "expected": "均为版本 2 文案"},
            ],
            expected_result="分组准确，文案版本与分组完全对应，无串组。",
            is_automated=True,
            created_by="增长组",
            created_at=datetime(2026, 3, 15, 10, 0, 0),
            updated_at=datetime(2026, 3, 15, 10, 0, 0),
        ),
        models.TestCase(
            name="短信召回退订用户过滤",
            directory_id=d_recall.id,
            description="已退订营销短信的用户不应出现在召回发送列表中。",
            priority=models.CasePriority.p0,
            tags=["召回", "短信", "合规"],
            status=models.StatusEnum.running,
            preconditions="用户 A 已回复 TD 退订；召回任务包含该用户",
            steps_manual=[
                {"seq": 1, "action": "触发短信召回任务", "expected": "任务执行完成"},
                {"seq": 2, "action": "检查用户 A 是否收到短信", "expected": "用户 A 不在发送列表，未收到短信"},
            ],
            expected_result="退订用户被过滤，合规要求满足。",
            is_automated=True,
            created_by="合规组",
            created_at=datetime(2026, 3, 18, 9, 0, 0),
            updated_at=datetime(2026, 3, 18, 9, 0, 0),
        ),
        models.TestCase(
            name="召回任务定时调度精度",
            directory_id=d_recall.id,
            description="每日 20:00 定时召回任务实际触发时间误差不超过 30 秒。",
            priority=models.CasePriority.p2,
            tags=["召回", "定时任务"],
            status=models.StatusEnum.running,
            preconditions="定时任务调度器正常运行",
            steps_manual=[
                {"seq": 1, "action": "在 20:00 前后观察任务触发时间", "expected": "任务在 20:00:00 ± 30s 内启动"},
                {"seq": 2, "action": "查询任务执行日志的 start_time", "expected": "误差 <= 30s"},
            ],
            expected_result="定时精度 <=30s，无漏触发。",
            is_automated=True,
            created_by="增长组",
            created_at=datetime(2026, 3, 20, 11, 0, 0),
            updated_at=datetime(2026, 3, 20, 11, 0, 0),
        ),
        models.TestCase(
            name="召回任务执行失败告警",
            directory_id=d_recall.id,
            description="召回任务执行失败（如下游发送接口异常）时，系统告警并记录失败原因，支持手动重试。",
            priority=models.CasePriority.p1,
            tags=["召回", "容错", "告警"],
            status=models.StatusEnum.running,
            preconditions="模拟 Push 发送接口返回 500",
            steps_manual=[
                {"seq": 1, "action": "触发召回任务，发送接口返回 500", "expected": "任务记录为失败状态"},
                {"seq": 2, "action": "检查告警通知", "expected": "收到失败告警，含任务 ID 和错误原因"},
                {"seq": 3, "action": "恢复发送接口后手动重试任务", "expected": "任务重新执行并成功"},
            ],
            expected_result="失败告警及时，重试机制可用。",
            is_automated=False,
            created_by="增长组",
            created_at=datetime(2026, 3, 22, 14, 0, 0),
            updated_at=datetime(2026, 3, 22, 14, 0, 0),
        ),
        models.TestCase(
            name="深度沉默用户分层召回",
            directory_id=d_recall.id,
            description="30 天未登录用户使用高权益优惠券召回，7-30 天用户使用普通文案，验证分层逻辑正确。",
            priority=models.CasePriority.p1,
            tags=["召回", "分层", "策略"],
            status=models.StatusEnum.running,
            preconditions="用户 A 最后登录 35 天前，用户 B 最后登录 15 天前",
            steps_manual=[
                {"seq": 1, "action": "触发召回任务", "expected": "任务执行成功"},
                {"seq": 2, "action": "查询用户 A 的召回消息", "expected": "收到高权益优惠券文案"},
                {"seq": 3, "action": "查询用户 B 的召回消息", "expected": "收到普通召回文案"},
            ],
            expected_result="分层准确，不同沉默深度用户收到对应策略的消息。",
            is_automated=True,
            created_by="增长组",
            created_at=datetime(2026, 3, 25, 10, 0, 0),
            updated_at=datetime(2026, 3, 25, 10, 0, 0),
        ),
        models.TestCase(
            name="召回 ROI 统计报表",
            directory_id=d_recall.id,
            description="召回任务完成后，ROI 报表应统计触达数、点击数、转化数及 ROI 比值，24 小时内可查。",
            priority=models.CasePriority.p2,
            tags=["召回", "ROI", "报表"],
            status=models.StatusEnum.running,
            preconditions="召回任务已完成，埋点数据已上报",
            steps_manual=[
                {"seq": 1, "action": "查询 GET /reports/recall/{task_id}", "expected": "HTTP 200"},
                {"seq": 2, "action": "检查字段：reach_count, click_count, convert_count, roi", "expected": "全部不为 null"},
                {"seq": 3, "action": "校验 roi = convert_revenue / send_cost", "expected": "计算结果与字段值一致"},
            ],
            expected_result="报表数据完整，ROI 计算公式正确。",
            is_automated=True,
            created_by="数据组",
            created_at=datetime(2026, 3, 28, 15, 0, 0),
            updated_at=datetime(2026, 3, 28, 15, 0, 0),
        ),
    ])

    d_ad = models.CaseDirectory(
        name="投放回传", path="投放回传", group_id=g_ops.id, sort_order=1
    )
    db.add(d_ad)
    db.flush()

    db.add_all([
        # ── 原有 3 条 ──
        models.TestCase(
            name="转化事件回传巨量引擎",
            directory_id=d_ad.id,
            description="用户完成注册转化后，回传事件在 5 分钟内到达巨量引擎，且事件类型、金额字段准确。",
            priority=models.CasePriority.p0,
            tags=["回传", "巨量", "转化"],
            status=models.StatusEnum.running,
            preconditions="巨量引擎 API Token 有效；回传服务已部署",
            steps_manual=[
                {"seq": 1, "action": "模拟用户完成注册", "expected": "业务侧记录转化事件"},
                {"seq": 2, "action": "等待 5 分钟后查询巨量引擎后台", "expected": "事件出现在转化列表"},
                {"seq": 3, "action": "核对事件类型和金额", "expected": "与业务侧一致，误差 < 1%"},
            ],
            expected_result="回传成功，5 分钟内可见，字段准确。",
            is_automated=True,
            created_by="投放组",
            created_at=datetime(2026, 4, 1, 9, 0, 0),
            updated_at=datetime(2026, 4, 28, 16, 0, 0),
            version=4,
        ),
        models.TestCase(
            name="回传去重幂等性验证",
            directory_id=d_ad.id,
            description="同一 order_id 的转化事件重复发送时，巨量引擎侧只记录一次，不重复计费。",
            priority=models.CasePriority.p1,
            tags=["回传", "幂等", "去重"],
            status=models.StatusEnum.running,
            preconditions="order_id=TEST001 的事件已成功回传一次",
            steps_manual=[
                {"seq": 1, "action": "再次发送 order_id=TEST001 的回传请求", "expected": "服务端返回 200"},
                {"seq": 2, "action": "查询巨量引擎转化记录", "expected": "TEST001 只出现一次"},
            ],
            expected_result="重复回传不导致重复计费，幂等性通过。",
            is_automated=True,
            created_by="投放组",
            created_at=datetime(2026, 4, 5, 11, 0, 0),
            updated_at=datetime(2026, 4, 5, 11, 0, 0),
        ),
        models.TestCase(
            name="回传失败自动重试机制",
            directory_id=d_ad.id,
            description="当回传接口超时或返回 5xx 时，系统在 1/5/15 分钟后自动重试，最多 3 次。",
            priority=models.CasePriority.p1,
            tags=["回传", "重试", "可靠性"],
            status=models.StatusEnum.debug,
            preconditions="模拟巨量引擎接口返回 503",
            steps_manual=[
                {"seq": 1, "action": "触发回传，接口返回 503", "expected": "系统记录失败，入重试队列"},
                {"seq": 2, "action": "等待 1 分钟", "expected": "系统发起第 1 次重试"},
                {"seq": 3, "action": "等待 5 分钟", "expected": "第 2 次重试"},
                {"seq": 4, "action": "恢复接口正常后等待 15 分钟", "expected": "第 3 次重试成功，事件回传完成"},
            ],
            expected_result="最终在第 3 次重试时成功回传，整体延迟 <= 21 分钟。",
            is_automated=False,
            created_by="投放组",
            created_at=datetime(2026, 4, 8, 14, 0, 0),
            updated_at=datetime(2026, 4, 8, 14, 0, 0),
        ),
        # ── 新增 7 条 ──
        models.TestCase(
            name="广点通转化事件回传",
            directory_id=d_ad.id,
            description="与巨量引擎同步，验证广点通（腾讯）渠道的转化事件回传时效与准确性。",
            priority=models.CasePriority.p0,
            tags=["回传", "广点通", "转化"],
            status=models.StatusEnum.running,
            preconditions="广点通 API 密钥有效",
            steps_manual=[
                {"seq": 1, "action": "模拟购买转化事件", "expected": "业务侧记录成功"},
                {"seq": 2, "action": "等待 10 分钟查询广点通", "expected": "事件可见，金额正确"},
            ],
            expected_result="广点通侧事件 10 分钟内可见，与业务数据一致。",
            is_automated=True,
            created_by="投放组",
            created_at=datetime(2026, 4, 10, 9, 0, 0),
            updated_at=datetime(2026, 4, 10, 9, 0, 0),
        ),
        models.TestCase(
            name="回传签名校验防篡改",
            directory_id=d_ad.id,
            description="回传请求使用 HMAC-SHA256 签名，验证签名校验正常工作，篡改请求被拒绝。",
            priority=models.CasePriority.p0,
            tags=["回传", "安全", "签名"],
            status=models.StatusEnum.running,
            preconditions="回传服务签名校验已启用",
            steps_manual=[
                {"seq": 1, "action": "发送正确签名的回传请求", "expected": "HTTP 200，回传成功"},
                {"seq": 2, "action": "篡改请求体后重新发送（签名不变）", "expected": "HTTP 400，签名校验失败"},
            ],
            expected_result="正确签名通过，篡改请求被拦截。",
            is_automated=True,
            created_by="安全组",
            created_at=datetime(2026, 4, 12, 10, 0, 0),
            updated_at=datetime(2026, 4, 12, 10, 0, 0),
        ),
        models.TestCase(
            name="多渠道同一订单回传去重",
            directory_id=d_ad.id,
            description="同一订单来自多个广告渠道归因时，每个渠道只计 1 次转化，总计不超过实际订单数。",
            priority=models.CasePriority.p1,
            tags=["回传", "多渠道", "去重"],
            status=models.StatusEnum.running,
            preconditions="订单 ORD-999 同时命中巨量和广点通归因",
            steps_manual=[
                {"seq": 1, "action": "触发 ORD-999 的回传流程", "expected": "两个渠道各自收到回传请求"},
                {"seq": 2, "action": "查询两个渠道的转化记录", "expected": "每个渠道各 1 条，无重复"},
            ],
            expected_result="每渠道仅计 1 次，无跨渠道重复计费。",
            is_automated=True,
            created_by="投放组",
            created_at=datetime(2026, 4, 15, 11, 0, 0),
            updated_at=datetime(2026, 4, 15, 11, 0, 0),
        ),
        models.TestCase(
            name="回传延迟监控报警",
            directory_id=d_ad.id,
            description="当回传平均延迟超过 10 分钟时，系统自动触发告警并记录到监控面板。",
            priority=models.CasePriority.p2,
            tags=["回传", "监控", "告警"],
            status=models.StatusEnum.running,
            preconditions="监控规则已配置，阈值 10 分钟",
            steps_manual=[
                {"seq": 1, "action": "模拟回传队列积压，延迟超过 10 分钟", "expected": "监控检测到延迟超阈值"},
                {"seq": 2, "action": "检查告警通知", "expected": "告警内容包含当前平均延迟和积压量"},
            ],
            expected_result="延迟超阈值时告警触发，内容准确。",
            is_automated=False,
            created_by="投放组",
            created_at=datetime(2026, 4, 18, 14, 0, 0),
            updated_at=datetime(2026, 4, 18, 14, 0, 0),
        ),
        models.TestCase(
            name="回传黑名单渠道过滤",
            directory_id=d_ad.id,
            description="被列入黑名单的广告渠道 ID 不应接收任何回传事件。",
            priority=models.CasePriority.p1,
            tags=["回传", "黑名单", "合规"],
            status=models.StatusEnum.running,
            preconditions="渠道 CH-9999 已被加入黑名单",
            steps_manual=[
                {"seq": 1, "action": "触发来源于 CH-9999 的转化事件", "expected": "回传服务识别黑名单渠道"},
                {"seq": 2, "action": "查询 CH-9999 的回传记录", "expected": "无任何回传请求发出"},
            ],
            expected_result="黑名单渠道不回传，其他渠道不受影响。",
            is_automated=True,
            created_by="合规组",
            created_at=datetime(2026, 4, 20, 10, 0, 0),
            updated_at=datetime(2026, 4, 20, 10, 0, 0),
        ),
        models.TestCase(
            name="Token 过期自动刷新后继续回传",
            directory_id=d_ad.id,
            description="广告平台 API Token 过期时，系统自动刷新 Token 并继续完成当前回传，无需人工干预。",
            priority=models.CasePriority.p1,
            tags=["回传", "Token", "自动化"],
            status=models.StatusEnum.running,
            preconditions="API Token 将在 1 分钟内过期",
            steps_manual=[
                {"seq": 1, "action": "在 Token 过期后触发回传事件", "expected": "系统检测到 401，自动刷新 Token"},
                {"seq": 2, "action": "等待刷新完成", "expected": "使用新 Token 重新发起回传，成功"},
            ],
            expected_result="Token 自动刷新，回传无中断，整体延迟增加 < 5s。",
            is_automated=True,
            created_by="投放组",
            created_at=datetime(2026, 4, 22, 16, 0, 0),
            updated_at=datetime(2026, 4, 22, 16, 0, 0),
        ),
        models.TestCase(
            name="回传数据对账日报",
            directory_id=d_ad.id,
            description="每日凌晨 01:00 自动生成对账日报，比对业务侧与广告平台侧数据差异，误差 < 0.1%。",
            priority=models.CasePriority.p2,
            tags=["回传", "对账", "报表"],
            status=models.StatusEnum.running,
            preconditions="对账任务调度器正常运行，T-1 数据已入库",
            steps_manual=[
                {"seq": 1, "action": "等待凌晨 01:00 后查询日报", "expected": "日报生成完成"},
                {"seq": 2, "action": "比对业务侧与平台侧转化数", "expected": "差异率 < 0.1%"},
                {"seq": 3, "action": "若有差异，检查差异明细表", "expected": "可定位到具体差异的 order_id"},
            ],
            expected_result="对账报表按时生成，差异率 < 0.1%，差异可溯源。",
            is_automated=True,
            created_by="数据组",
            created_at=datetime(2026, 4, 25, 9, 0, 0),
            updated_at=datetime(2026, 4, 25, 9, 0, 0),
        ),
    ])

    db.commit()
